// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lista7_zad1.Context;

#nullable disable

namespace lista7_zad1.Migrations
{
    [DbContext(typeof(StudentsDbContext))]
    [Migration("20230614172448_RemoveStudentPWD")]
    partial class RemoveStudentPWD
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("lista7_zad1.Models.Admin", b =>
                {
                    b.Property<int>("AdminID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Login")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.HasKey("AdminID");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("lista7_zad1.Models.Classification", b =>
                {
                    b.Property<int>("ClassificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("ClassificationID");

                    b.ToTable("Classifications");
                });

            modelBuilder.Entity("lista7_zad1.Models.Grade", b =>
                {
                    b.Property<int>("GradeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClassificationID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("GradeValID")
                        .HasColumnType("int");

                    b.Property<int>("ProfessorID")
                        .HasColumnType("int");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.Property<int>("SubjectID")
                        .HasColumnType("int");

                    b.HasKey("GradeID");

                    b.HasIndex("ClassificationID");

                    b.HasIndex("GradeValID");

                    b.HasIndex("ProfessorID");

                    b.HasIndex("StudentID");

                    b.HasIndex("SubjectID");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("lista7_zad1.Models.GradeVal", b =>
                {
                    b.Property<int>("GradeValID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<double?>("Value")
                        .HasColumnType("double");

                    b.HasKey("GradeValID");

                    b.ToTable("GradeVals");
                });

            modelBuilder.Entity("lista7_zad1.Models.Major", b =>
                {
                    b.Property<int>("MajorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("MajorID");

                    b.ToTable("Majors");
                });

            modelBuilder.Entity("lista7_zad1.Models.People", b =>
                {
                    b.Property<int>("OsobaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Surname")
                        .HasColumnType("longtext");

                    b.HasKey("OsobaId");

                    b.ToTable("Osoby");
                });

            modelBuilder.Entity("lista7_zad1.Models.Professor", b =>
                {
                    b.Property<int>("ProfessorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AlbumNr")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<int>("PeopleID")
                        .HasColumnType("int");

                    b.HasKey("ProfessorID");

                    b.HasIndex("PeopleID");

                    b.ToTable("Professors");
                });

            modelBuilder.Entity("lista7_zad1.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AlbumNr")
                        .HasColumnType("longtext");

                    b.Property<int>("MajorID")
                        .HasColumnType("int");

                    b.Property<int>("PeopleID")
                        .HasColumnType("int");

                    b.HasKey("StudentId");

                    b.HasIndex("MajorID");

                    b.HasIndex("PeopleID");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("lista7_zad1.Models.Subject", b =>
                {
                    b.Property<int>("SubjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("SubjectID");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("lista7_zad1.Models.Grade", b =>
                {
                    b.HasOne("lista7_zad1.Models.Classification", "Classification")
                        .WithMany("Grades")
                        .HasForeignKey("ClassificationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lista7_zad1.Models.GradeVal", "GradeVal")
                        .WithMany("Grades")
                        .HasForeignKey("GradeValID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lista7_zad1.Models.Professor", "Professor")
                        .WithMany("Grades")
                        .HasForeignKey("ProfessorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lista7_zad1.Models.Student", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lista7_zad1.Models.Subject", "Subject")
                        .WithMany("Grades")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classification");

                    b.Navigation("GradeVal");

                    b.Navigation("Professor");

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("lista7_zad1.Models.Professor", b =>
                {
                    b.HasOne("lista7_zad1.Models.People", "People")
                        .WithMany("Professors")
                        .HasForeignKey("PeopleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("People");
                });

            modelBuilder.Entity("lista7_zad1.Models.Student", b =>
                {
                    b.HasOne("lista7_zad1.Models.Major", "Major")
                        .WithMany("Students")
                        .HasForeignKey("MajorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lista7_zad1.Models.People", "People")
                        .WithMany("Students")
                        .HasForeignKey("PeopleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Major");

                    b.Navigation("People");
                });

            modelBuilder.Entity("lista7_zad1.Models.Classification", b =>
                {
                    b.Navigation("Grades");
                });

            modelBuilder.Entity("lista7_zad1.Models.GradeVal", b =>
                {
                    b.Navigation("Grades");
                });

            modelBuilder.Entity("lista7_zad1.Models.Major", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("lista7_zad1.Models.People", b =>
                {
                    b.Navigation("Professors");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("lista7_zad1.Models.Professor", b =>
                {
                    b.Navigation("Grades");
                });

            modelBuilder.Entity("lista7_zad1.Models.Student", b =>
                {
                    b.Navigation("Grades");
                });

            modelBuilder.Entity("lista7_zad1.Models.Subject", b =>
                {
                    b.Navigation("Grades");
                });
#pragma warning restore 612, 618
        }
    }
}
